# Generated by Django 4.2.24 on 2025-09-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Category name", max_length=100)),
                (
                    "slug",
                    models.SlugField(help_text="URL slug", max_length=120, unique=True),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Category description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Media Category",
                "verbose_name_plural": "Media Categories",
                "ordering": ["name"],
            },
        ),
    ]
