# Generated by Django 4.2.24 on 2025-09-07 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0004_pagerevision_auditentry"),
        ("i18n", "0003_translationunit_uimessage_uimessagetranslation_and_more"),
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="presentation_page",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional presentation page override for this category",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="category_presentations",
                to="cms.page",
            ),
        ),
        migrations.CreateModel(
            name="BlogSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_path",
                    models.CharField(
                        default="blog",
                        help_text="Base path for blog URLs (without leading/trailing slashes)",
                        max_length=100,
                    ),
                ),
                (
                    "design_tokens",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='\n    Design configuration, e.g.:\n    {\n        "content_width": "prose",\n        "typography_scale": "md",\n        "accent_color": "#3b82f6"\n    }\n    ',
                    ),
                ),
                (
                    "show_toc",
                    models.BooleanField(
                        default=True, help_text="Show table of contents by default"
                    ),
                ),
                (
                    "show_author",
                    models.BooleanField(
                        default=True, help_text="Show author information by default"
                    ),
                ),
                (
                    "show_dates",
                    models.BooleanField(
                        default=True, help_text="Show publication dates by default"
                    ),
                ),
                (
                    "show_share",
                    models.BooleanField(
                        default=True, help_text="Show social sharing buttons by default"
                    ),
                ),
                (
                    "show_reading_time",
                    models.BooleanField(
                        default=True, help_text="Show estimated reading time by default"
                    ),
                ),
                (
                    "feeds_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='\n    RSS/Atom feed configuration, e.g.:\n    {\n        "title": "My Blog",\n        "description": "Latest posts from my blog",\n        "items_per_feed": 20\n    }\n    ',
                    ),
                ),
                (
                    "seo_defaults",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='\n    Default SEO settings for blog posts, e.g.:\n    {\n        "title_template": "{title} - Blog",\n        "meta_description_template": "Read about {title} on our blog"\n    }\n    ',
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_presentation_page",
                    models.ForeignKey(
                        blank=True,
                        help_text="Default presentation page template for blog posts",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blog_presentations",
                        to="cms.page",
                    ),
                ),
                (
                    "locale",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_settings",
                        to="i18n.locale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Settings",
                "verbose_name_plural": "Blog Settings",
            },
        ),
    ]
