# Generated by Django 4.2.24 on 2025-09-07 15:20


from django.db import migrations, models

import apps.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_add_performance_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="blocks",
            field=models.JSONField(
                default=list,
                help_text="Structured content blocks",
                validators=[
                    # Imports that were malformed - commented out
                    #                     """apps.core.validators.JSONSizeValidator(5),"""
                    # Imports that were malformed - commented out
                    #                     """apps.core.validators.validate_json_structure,"""
                ],
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="seo",
            field=models.JSONField(
                default=dict,
                help_text="SEO metadata including title, description, and image",
                validators=[apps.core.validators.JSONSizeValidator(0.5)],
            ),
        ),
    ]
