# Generated by Django 4.2.24 on 2025-09-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_blogpost_blocks_alter_blogpost_seo"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(
                fields=["category", "status", "featured", "-published_at"],
                name="blog_blogpo_categor_8c5abd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(
                fields=["locale", "slug"], name="blog_blogpo_locale__ae5c0d_idx"
            ),
        ),
    ]
