# Generated by Django 4.2.24 on 2025-09-08 07:44

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0005_add_performance_indexes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={
                "ordering": ["-published_at", "-created_at"],
                "permissions": [
                    ("publish_blogpost", "Can publish blog posts"),
                    ("unpublish_blogpost", "Can unpublish blog posts"),
                    ("feature_blogpost", "Can feature blog posts"),
                    ("moderate_comments", "Can moderate blog comments"),
                    ("bulk_delete_blogpost", "Can bulk delete blog posts"),
                ],
                "verbose_name": "Blog Post",
                "verbose_name_plural": "Blog Posts",
            },
        ),
        migrations.CreateModel(
            name="BlogPostViewTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Total view count"
                    ),
                ),
                (
                    "unique_view_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Unique visitor count (approximate)"
                    ),
                ),
                (
                    "last_viewed",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time this post was viewed",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "blog_post",
                    models.OneToOneField(
                        help_text="Blog post being tracked",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_tracker",
                        to="blog.blogpost",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Post View Tracker",
                "verbose_name_plural": "Blog Post View Trackers",
            },
        ),
        migrations.CreateModel(
            name="BlogPostRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "snapshot",
                    models.JSONField(
                        help_text="Complete blog post data snapshot including content, blocks, and metadata"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_published_snapshot",
                    models.BooleanField(
                        default=False,
                        help_text="True if this revision represents a published state",
                    ),
                ),
                (
                    "is_autosave",
                    models.BooleanField(
                        default=False,
                        help_text="True if this revision was created by autosave",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, help_text="Optional comment about this revision"
                    ),
                ),
                (
                    "blog_post",
                    models.ForeignKey(
                        help_text="Blog post this revision belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="blog.blogpost",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this revision",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blog_post_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Post Revision",
                "verbose_name_plural": "Blog Post Revisions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["blog_post", "-created_at"],
                        name="blog_blogpo_blog_po_1bc318_idx",
                    ),
                    models.Index(
                        fields=["blog_post", "is_published_snapshot"],
                        name="blog_blogpo_blog_po_dfd936_idx",
                    ),
                    models.Index(
                        fields=["created_by", "-created_at"],
                        name="blog_blogpo_created_9923ce_idx",
                    ),
                    models.Index(
                        fields=["is_published_snapshot", "-created_at"],
                        name="blog_blogpo_is_publ_ccf86a_idx",
                    ),
                ],
            },
        ),
        # Add index for view tracker (now that the model exists)
        migrations.AddIndex(
            model_name="blogpostviewtracker",
            index=models.Index(
                fields=["blog_post", "-last_viewed"], name="blog_view_tracker_idx"
            ),
        ),
    ]
