# Generated by Django 4.2.24 on 2025-09-08 08:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_add_custom_permissions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ["name"],
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
    ]
