# Generated by Django 4.2.24 on 2025-09-08 12:06


import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
        ("blog", "0008_alter_category_options_alter_tag_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="social_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Image for social media sharing",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blog_post_social_images",
                to="files.fileupload",
            ),
        ),
        migrations.AlterField(
            model_name="blogsettings",
            name="design_tokens",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Design configuration, e.g.: {"content_width": "prose", "typography_scale": "md", "accent_color": "#3b82f6"}',
            ),
        ),
        migrations.AlterField(
            model_name="blogsettings",
            name="feeds_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='RSS/Atom feed configuration, e.g.: {"title": "My Blog", "description": "Latest posts from my blog", "items_per_feed": 20}',
            ),
        ),
        migrations.AlterField(
            model_name="blogsettings",
            name="seo_defaults",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Default SEO settings for blog posts, e.g.: {"title_template": "{title} - Blog", "meta_description_template": "Read about {title} on our blog"}',
            ),
        ),
    ]
