# Generated by Django 4.2.24 on 2025-09-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_alter_blogpost_social_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="scheduled_for",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="scheduled_publish_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When to automatically publish this post",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="scheduled_unpublish_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When to automatically unpublish this post",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="published_at",
            field=models.DateTimeField(
                blank=True, help_text="When this post was actually published", null=True
            ),
        ),
    ]
