# Generated by Django 4.2.24 on 2025-09-14 04:59

from django.db import migrations, models

import apps.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_migrate_scheduling_data"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="blogpost",
            name="blog_post_featured_idx",
        ),
        migrations.RemoveIndex(
            model_name="blogpost",
            name="blog_post_category_idx",
        ),
        migrations.RemoveIndex(
            model_name="blogpost",
            name="blog_post_author_idx",
        ),
        migrations.RemoveIndex(
            model_name="blogpost",
            name="blog_post_list_idx",
        ),
        migrations.RemoveIndex(
            model_name="blogpostviewtracker",
            name="blog_view_tracker_idx",
        ),
        migrations.RemoveIndex(
            model_name="category",
            name="blog_category_slug_idx",
        ),
        migrations.RemoveIndex(
            model_name="tag",
            name="blog_tag_slug_idx",
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="blocks",
            field=models.JSONField(
                default=list,
                help_text="Structured content blocks",
                validators=[
                    apps.core.validators.JSONSizeValidator(5),
                    apps.core.validators.validate_json_structure,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
