# Generated by Django 4.2.24 on 2025-09-07 02:54


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("i18n", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="locale",
            options={"ordering": ["sort_order", "name"]},
        ),
        migrations.AddField(
            model_name="locale",
            name="fallback",
            field=models.ForeignKey(
                blank=True,
                help_text="Fallback locale if content is not available in this locale",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="i18n.locale",
            ),
        ),
        migrations.AddField(
            model_name="locale",
            name="native_name",
            field=models.CharField(
                default="",
                help_text="Native name in the language itself (e.g., 'English', 'Español', 'Français')",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="locale",
            name="rtl",
            field=models.BooleanField(
                default=False,
                help_text="True if this is a right-to-left language (e.g., Arabic, Hebrew)",
            ),
        ),
        migrations.AddField(
            model_name="locale",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0, help_text="Sort order for locale lists (lower numbers first)"
            ),
        ),
        migrations.AddField(
            model_name="locale",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="locale",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether this locale is active and available for use",
            ),
        ),
        migrations.AlterField(
            model_name="locale",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="Whether this is the default locale for the site",
            ),
        ),
        migrations.AlterField(
            model_name="locale",
            name="name",
            field=models.CharField(
                help_text="Human-readable name in English (e.g., 'English', 'Spanish')",
                max_length=100,
            ),
        ),
        migrations.AddIndex(
            model_name="locale",
            index=models.Index(
                fields=["is_active", "sort_order"],
                name="i18n_locale_is_acti_5367ad_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="locale",
            index=models.Index(
                fields=["is_default"], name="i18n_locale_is_defa_8dcb0e_idx"
            ),
        ),
    ]
