# Generated by Django 4.2.24 on 2025-09-07 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("i18n", "0002_alter_locale_options_locale_fallback_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranslationUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "field",
                    models.CharField(
                        help_text="Name of the field being translated (e.g., 'title', 'blocks')",
                        max_length=100,
                    ),
                ),
                (
                    "source_text",
                    models.TextField(help_text="Original text in source locale"),
                ),
                (
                    "target_text",
                    models.TextField(
                        blank=True, help_text="Translated text in target locale"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("missing", "Missing"),
                            ("draft", "Draft"),
                            ("needs_review", "Needs Review"),
                            ("approved", "Approved"),
                        ],
                        default="missing",
                        help_text="Translation status",
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="UiMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Unique key for this message (e.g., 'auth.login.title')",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "namespace",
                    models.CharField(
                        default="general",
                        help_text="Namespace for organizing messages (e.g., 'auth', 'cms', 'general')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of when/where this message is used",
                    ),
                ),
                (
                    "default_value",
                    models.TextField(help_text="Default text in the default locale"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["namespace", "key"],
            },
        ),
        migrations.CreateModel(
            name="UiMessageTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField(help_text="Translated message text")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("missing", "Missing"),
                            ("draft", "Draft"),
                            ("needs_review", "Needs Review"),
                            ("approved", "Approved"),
                        ],
                        default="draft",
                        help_text="Translation status",
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "locale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ui_translations",
                        to="i18n.locale",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="i18n.uimessage",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this translation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["message__namespace", "message__key"],
            },
        ),
        migrations.AddIndex(
            model_name="uimessage",
            index=models.Index(
                fields=["namespace"], name="i18n_uimess_namespa_76e8ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uimessage",
            index=models.Index(fields=["key"], name="i18n_uimess_key_bb1717_idx"),
        ),
        migrations.AddField(
            model_name="translationunit",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="translationunit",
            name="source_locale",
            field=models.ForeignKey(
                help_text="Locale of the source content",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source_translations",
                to="i18n.locale",
            ),
        ),
        migrations.AddField(
            model_name="translationunit",
            name="target_locale",
            field=models.ForeignKey(
                help_text="Locale being translated to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="target_translations",
                to="i18n.locale",
            ),
        ),
        migrations.AddField(
            model_name="translationunit",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last updated this translation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="uimessagetranslation",
            index=models.Index(
                fields=["locale", "status"], name="i18n_uimess_locale__a593a1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="uimessagetranslation",
            unique_together={("message", "locale")},
        ),
        migrations.AddIndex(
            model_name="translationunit",
            index=models.Index(
                fields=["content_type", "object_id", "field"],
                name="i18n_transl_content_4a5060_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="translationunit",
            index=models.Index(
                fields=["target_locale", "status"],
                name="i18n_transl_target__ba7b1f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="translationunit",
            index=models.Index(
                fields=["source_locale", "target_locale"],
                name="i18n_transl_source__09c6ac_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="translationunit",
            unique_together={
                ("content_type", "object_id", "field", "source_locale", "target_locale")
            },
        ),
    ]
