# Generated by Django 4.2.24 on 2025-09-08 05:47


import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("i18n", "0003_translationunit_uimessage_uimessagetranslation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translationunit",
            name="status",
            field=models.CharField(
                choices=[
                    ("missing", "Missing"),
                    ("draft", "Draft"),
                    ("needs_review", "Needs Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="missing",
                help_text="Translation status",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="TranslationQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        help_text="Current status in the translation workflow",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        help_text="Priority level for this translation task",
                        max_length=10,
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deadline for completing this translation",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes about this translation task",
                    ),
                ),
                (
                    "machine_translation_suggestion",
                    models.TextField(
                        blank=True,
                        help_text="Machine translation suggestion for reference",
                    ),
                ),
                (
                    "mt_service",
                    models.CharField(
                        blank=True,
                        help_text="Machine translation service used (e.g., 'google', 'deepl', 'azure')",
                        max_length=50,
                    ),
                ),
                (
                    "word_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Word count of source text for effort estimation",
                    ),
                ),
                (
                    "estimated_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated hours to complete this translation",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="User assigned to translate this content",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_translations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who added this item to the queue",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="queued_translations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "translation_unit",
                    models.OneToOneField(
                        help_text="Translation unit to be processed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_item",
                        to="i18n.translationunit",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "priority", "-created_at"],
                        name="i18n_transl_status_7994f4_idx",
                    ),
                    models.Index(
                        fields=["assigned_to", "status"],
                        name="i18n_transl_assigne_92b0fd_idx",
                    ),
                    models.Index(
                        fields=["deadline"], name="i18n_transl_deadlin_12e97e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TranslationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("status_changed", "Status Changed"),
                            ("assigned", "Assigned"),
                        ],
                        help_text="Type of action performed",
                        max_length=20,
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        blank=True,
                        help_text="Previous status before the change",
                        max_length=20,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        blank=True,
                        help_text="New status after the change",
                        max_length=20,
                    ),
                ),
                (
                    "previous_target_text",
                    models.TextField(
                        blank=True, help_text="Previous target text before the change"
                    ),
                ),
                (
                    "new_target_text",
                    models.TextField(
                        blank=True, help_text="New target text after the change"
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, help_text="Optional comment explaining the change"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        help_text="User who performed this action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "translation_unit",
                    models.ForeignKey(
                        help_text="Translation unit this history entry belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="i18n.translationunit",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Translation histories",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["translation_unit", "-created_at"],
                        name="i18n_transl_transla_a5fed2_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="i18n_transl_action_a830fa_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TranslationGlossary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        help_text="Original term or phrase", max_length=200
                    ),
                ),
                (
                    "translation",
                    models.CharField(
                        help_text="Translated term or phrase", max_length=200
                    ),
                ),
                (
                    "context",
                    models.TextField(
                        blank=True,
                        help_text="Context or usage notes for this translation",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        default="general",
                        help_text="Category for organizing terms (e.g., 'ui', 'technical', 'brand')",
                        max_length=100,
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this translation has been verified by a linguist",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this glossary entry",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="glossary_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_locale",
                    models.ForeignKey(
                        help_text="Source locale of the term",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="glossary_source_terms",
                        to="i18n.locale",
                    ),
                ),
                (
                    "target_locale",
                    models.ForeignKey(
                        help_text="Target locale for translation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="glossary_target_terms",
                        to="i18n.locale",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        help_text="User who last updated this glossary entry",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="glossary_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Translation glossaries",
                "ordering": ["term"],
                "indexes": [
                    models.Index(fields=["term"], name="i18n_transl_term_1a830c_idx"),
                    models.Index(
                        fields=["source_locale", "target_locale"],
                        name="i18n_transl_source__b4209e_idx",
                    ),
                    models.Index(
                        fields=["category"], name="i18n_transl_categor_131a76_idx"
                    ),
                    models.Index(
                        fields=["is_verified"], name="i18n_transl_is_veri_0c0268_idx"
                    ),
                ],
                "unique_together": {("term", "source_locale", "target_locale")},
            },
        ),
    ]
