# Generated by Django 4.2.24 on 2025-09-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("i18n", "0005_create_default_locale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locale",
            name="native_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Native name in the language itself (e.g., 'English', 'Español', 'Français')",
                max_length=100,
            ),
        ),
    ]
