# Generated by Django 4.2.24 on 2025-09-07 02:10


import uuid


import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("i18n", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Redirect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_path", models.CharField(db_index=True, max_length=512)),
                ("to_path", models.CharField(max_length=512)),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(301, "301 Permanent"), (302, "302 Temporary")],
                        default=301,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "locale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="i18n.locale",
                    ),
                ),
            ],
            options={
                "unique_together": {("from_path", "locale")},
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("group_id", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("position", models.PositiveIntegerField(db_index=True, default=0)),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField(max_length=120)),
                ("path", models.CharField(db_index=True, max_length=512)),
                ("blocks", models.JSONField(default=list)),
                ("seo", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("scheduled", "Scheduled"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("preview_token", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "locale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="i18n.locale"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="cms.page",
                    ),
                ),
            ],
            options={
                "ordering": ["parent_id", "position", "id"],
                "indexes": [
                    models.Index(
                        fields=["group_id", "locale"],
                        name="cms_page_group_i_e3c345_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="page",
            constraint=models.UniqueConstraint(
                fields=("locale", "parent", "slug"), name="uq_page_slug_parent_locale"
            ),
        ),
    ]
