# Generated by Django 4.2.24 on 2025-09-07 02:20

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ("i18n", "0001_initial"),
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeoSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_suffix",
                    models.CharField(
                        blank=True,
                        help_text="Appended to page titles (e.g., ' - My Site')",
                        max_length=120,
                    ),
                ),
                (
                    "default_description",
                    models.TextField(
                        blank=True,
                        help_text="Default meta description for pages without one",
                    ),
                ),
                (
                    "robots_default",
                    models.CharField(
                        default="index,follow",
                        help_text="Default robots directive",
                        max_length=64,
                    ),
                ),
                (
                    "jsonld_default",
                    models.JSONField(
                        default=list, help_text="Default JSON-LD structured data blocks"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "locale",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seo_settings",
                        to="i18n.locale",
                    ),
                ),
            ],
            options={
                "verbose_name": "SEO Settings",
                "verbose_name_plural": "SEO Settings",
            },
        ),
        migrations.CreateModel(
            name="SeoDefaults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path_prefix",
                    models.CharField(
                        help_text="Path prefix (e.g., '/blog' or '/products')",
                        max_length=255,
                    ),
                ),
                (
                    "overrides",
                    models.JSONField(
                        default=dict,
                        help_text="SEO overrides in same format as page seo field",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "locale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seo_defaults",
                        to="i18n.locale",
                    ),
                ),
            ],
            options={
                "verbose_name": "SEO Defaults",
                "verbose_name_plural": "SEO Defaults",
                "ordering": ["-path_prefix"],
                "indexes": [
                    models.Index(
                        fields=["locale", "path_prefix"],
                        name="cms_seodefa_locale__1d920d_idx",
                    )
                ],
            },
        ),
    ]
