# Generated by Django 4.2.24 on 2025-09-07 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
        ("cms", "0002_seosettings_seodefaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="seosettings",
            name="default_og_asset",
            field=models.ForeignKey(
                blank=True,
                help_text="Default Open Graph image",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="seo_defaults",
                to="media.asset",
            ),
        ),
    ]
