# Generated by Django 4.2.24 on 2025-09-07 03:07

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("cms", "0003_seosettings_default_og_asset"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "snapshot",
                    models.JSONField(
                        help_text="Complete page data snapshot including blocks, seo, and metadata"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_published_snapshot",
                    models.BooleanField(
                        default=False,
                        help_text="True if this revision represents a published state",
                    ),
                ),
                (
                    "is_autosave",
                    models.BooleanField(
                        default=False,
                        help_text="True if this revision was created by autosave",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, help_text="Optional comment about this revision"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this revision",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="page_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        help_text="Page this revision belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="cms.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page Revision",
                "verbose_name_plural": "Page Revisions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["page", "-created_at"],
                        name="cms_pagerev_page_id_f6c06c_idx",
                    ),
                    models.Index(
                        fields=["page", "is_published_snapshot"],
                        name="cms_pagerev_page_id_cef708_idx",
                    ),
                    models.Index(
                        fields=["created_by", "-created_at"],
                        name="cms_pagerev_created_e8caa9_idx",
                    ),
                    models.Index(
                        fields=["is_published_snapshot", "-created_at"],
                        name="cms_pagerev_is_publ_94daf8_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("publish", "Publish"),
                            ("unpublish", "Unpublish"),
                            ("move", "Move"),
                            ("revert", "Revert"),
                            ("duplicate", "Duplicate"),
                        ],
                        help_text="Type of action performed",
                        max_length=20,
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "model_label",
                    models.CharField(
                        help_text="App.Model format (e.g., 'cms.Page')", max_length=100
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "meta",
                    models.JSONField(
                        default=dict, help_text="Additional metadata about the action"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Entry",
                "verbose_name_plural": "Audit Entries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["actor", "-created_at"],
                        name="cms_auditen_actor_i_bbebc1_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id", "-created_at"],
                        name="cms_auditen_content_ccf7c9_idx",
                    ),
                    models.Index(
                        fields=["model_label", "object_id", "-created_at"],
                        name="cms_auditen_model_l_4f9bf2_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="cms_auditen_action_b9bf9f_idx",
                    ),
                ],
            },
        ),
    ]
