# Generated by Django 4.2.24 on 2025-09-07 15:20

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0004_pagerevision_auditentry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="blocks",
            field=models.JSONField(
                default=list,
                validators=[
                    apps.core.validators.JSONSizeValidator(2),
                    apps.core.validators.validate_json_structure,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="seo",
            field=models.JSONField(
                default=dict, validators=[apps.core.validators.JSONSizeValidator(0.5)]
            ),
        ),
    ]
