# Generated by Django 4.2.24 on 2025-09-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0005_alter_page_blocks_alter_page_seo"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="page",
            index=models.Index(
                fields=["locale", "path"], name="cms_page_locale__7c3063_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="page",
            index=models.Index(
                fields=["locale", "status", "-updated_at"],
                name="cms_page_locale__ef5b7b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="page",
            index=models.Index(
                fields=["parent", "position"], name="cms_page_parent__351dd8_idx"
            ),
        ),
    ]
