# Generated by Django 4.2.24 on 2025-09-08 08:06


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0008_add_custom_permissions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="redirect",
            options={},
        ),
    ]
