# Generated by Django 4.2.24 on 2025-09-09 04:23


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0009_alter_redirect_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SeoDefaults",
        ),
    ]
