# Generated by Django 4.2.24 on 2025-09-09 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cms", "0010_delete_seodefaults"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={
                "ordering": ["parent_id", "position", "id"],
                "permissions": [
                    ("publish_page", "Can publish pages"),
                    ("unpublish_page", "Can unpublish pages"),
                    ("preview_page", "Can preview draft pages"),
                    ("revert_page", "Can revert page to previous version"),
                    ("translate_page", "Can translate pages"),
                    ("manage_page_seo", "Can manage page SEO settings"),
                    ("bulk_delete_pages", "Can bulk delete pages"),
                    ("export_pages", "Can export pages"),
                    ("import_pages", "Can import pages"),
                    ("moderate_content", "Can moderate content"),
                    ("approve_content", "Can approve content"),
                    ("reject_content", "Can reject content"),
                    ("view_moderation_queue", "Can view moderation queue"),
                    ("schedule_content", "Can schedule content"),
                ],
            },
        ),
        migrations.AddField(
            model_name="page",
            name="review_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="page",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_pages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="submitted_for_review_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="page",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_review", "Pending Review"),
                    ("approved", "Approved"),
                    ("published", "Published"),
                    ("scheduled", "Scheduled"),
                    ("rejected", "Rejected"),
                ],
                default="draft",
                max_length=15,
            ),
        ),
        migrations.AddIndex(
            model_name="page",
            index=models.Index(
                fields=["status", "submitted_for_review_at"],
                name="cms_page_status_e2bd4a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="page",
            index=models.Index(
                fields=["reviewed_by", "status"], name="cms_page_reviewe_b48d9f_idx"
            ),
        ),
    ]
