# Generated by Django 4.2.24 on 2025-09-10 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0011_alter_page_options_page_review_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="redirect",
            name="hits",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of times this redirect has been used"
            ),
        ),
        migrations.AddField(
            model_name="redirect",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Enable or disable this redirect"
            ),
        ),
        migrations.AddField(
            model_name="redirect",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Optional notes about this redirect", null=True
            ),
        ),
        migrations.AlterField(
            model_name="redirect",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (301, "301 Permanent"),
                    (302, "302 Temporary"),
                    (307, "307 Temporary Preserve"),
                    (308, "308 Permanent Preserve"),
                ],
                default=301,
            ),
        ),
    ]
