# Generated by Django 4.2.24 on 2025-09-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0012_redirect_hits_redirect_is_active_redirect_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="in_footer",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="page",
            name="in_main_menu",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="page",
            name="is_homepage",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
