# Generated by Django 4.2.24 on 2025-09-10 01:16


import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
        ("cms", "0013_page_in_footer_page_in_main_menu_page_is_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="seosettings",
            name="bing_site_verification",
            field=models.CharField(
                blank=True,
                help_text="Bing Webmaster Tools verification code",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="seosettings",
            name="canonical_domain",
            field=models.CharField(
                blank=True,
                help_text="Canonical domain for URLs (e.g., https://example.com)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="seosettings",
            name="default_keywords",
            field=models.CharField(
                blank=True,
                help_text="Default meta keywords (comma-separated)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="seosettings",
            name="default_og_description",
            field=models.TextField(
                blank=True, help_text="Default Open Graph description"
            ),
        ),
        migrations.AddField(
            model_name="seosettings",
            name="default_og_site_name",
            field=models.CharField(
                blank=True, help_text="Site name for Open Graph", max_length=120
            ),
        ),
        migrations.AddField(
            model_name="seosettings",
            name="default_og_title",
            field=models.CharField(
                blank=True, help_text="Default Open Graph title", max_length=120
            ),
        ),
        migrations.AddField(
            model_name="seosettings",
            name="default_og_type",
            field=models.CharField(
                default="website", help_text="Default Open Graph type", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="seosettings",
            name="default_title",
            field=models.CharField(
                blank=True,
                help_text="Default page title when none is set",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="seosettings",
            name="default_twitter_asset",
            field=models.ForeignKey(
                blank=True,
                help_text="Default Twitter card image",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="twitter_seo_defaults",
                to="media.asset",
            ),
        ),
        migrations.AddField(
            model_name="seosettings",
            name="default_twitter_card",
            field=models.CharField(
                choices=[
                    ("summary", "Summary"),
                    ("summary_large_image", "Summary with Large Image"),
                    ("app", "App"),
                    ("player", "Player"),
                ],
                default="summary_large_image",
                help_text="Default Twitter card type",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="seosettings",
            name="default_twitter_creator",
            field=models.CharField(
                blank=True,
                help_text="Twitter @username for content creator",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="seosettings",
            name="default_twitter_site",
            field=models.CharField(
                blank=True, help_text="Twitter @username for the site", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="seosettings",
            name="facebook_app_id",
            field=models.CharField(
                blank=True, help_text="Facebook App ID", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="seosettings",
            name="google_site_verification",
            field=models.CharField(
                blank=True,
                help_text="Google Search Console verification code",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="seosettings",
            name="meta_author",
            field=models.CharField(
                blank=True, help_text="Default author meta tag", max_length=120
            ),
        ),
        migrations.AddField(
            model_name="seosettings",
            name="meta_generator",
            field=models.CharField(
                blank=True, help_text="Generator meta tag", max_length=120
            ),
        ),
        migrations.AddField(
            model_name="seosettings",
            name="meta_viewport",
            field=models.CharField(
                default="width=device-width, initial-scale=1.0",
                help_text="Viewport meta tag",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="seosettings",
            name="organization_jsonld",
            field=models.JSONField(
                blank=True, default=dict, help_text="Organization schema.org data"
            ),
        ),
    ]
