# Generated by Django 4.2.24 on 2025-09-10 12:15


import django.db.models.deletion

from django.conf import settings

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        """migrations.swappable_dependency(settings.AUTH_USER_MODEL),"""
        ("cms", "0015_fix_file_references"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="scheduled_publish_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When to automatically publish this page",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="scheduled_unpublish_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When to automatically unpublish this page",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="published_at",
            field=models.DateTimeField(
                blank=True, help_text="When this page was actually published", null=True
            ),
        ),
        migrations.CreateModel(
            name="ScheduledTask",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("object_id", models.PositiveIntegerField()),
                (
                    "task_type",
                    models.CharField(
                        choices=[("publish", "Publish"), ("unpublish", "Unpublish")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("scheduled_for", models.DateTimeField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheduled_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheduled Task",
                "verbose_name_plural": "Scheduled Tasks",
                "ordering": ["scheduled_for"],
                "indexes": [
                    models.Index(
                        fields=["status", "scheduled_for"],
                        name="cms_schedul_status_adb32f_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id", "task_type"],
                        name="cms_schedul_content_01c400_idx",
                    ),
                    models.Index(
                        fields=["status", "task_type", "-scheduled_for"],
                        name="cms_schedul_status_79f9da_idx",
                    ),
                ],
            },
        ),
    ]
