# Generated by Django 4.2.24 on 2025-09-10 15:27


import django.db.models.deletion

from django.conf import settings

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cms", "0017_migrate_scheduling_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        help_text='Unique identifier for this block type (e.g., "hero", "richtext")',
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "component",
                    models.CharField(
                        help_text='Frontend component name (e.g., "HeroBlock", "RichtextBlock")',
                        max_length=100,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Human-readable label shown in the editor",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of what this block does"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("layout", "Layout"),
                            ("content", "Content"),
                            ("media", "Media"),
                            ("marketing", "Marketing"),
                            ("dynamic", "Dynamic"),
                            ("other", "Other"),
                        ],
                        default="content",
                        help_text="Category for organizing blocks in the editor",
                        max_length=20,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="square",
                        help_text="Icon identifier (Lucide icon name)",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this block type is available in the editor",
                    ),
                ),
                (
                    "preload",
                    models.BooleanField(
                        default=False,
                        help_text="Whether to preload this component for better performance",
                    ),
                ),
                (
                    "editing_mode",
                    models.CharField(
                        choices=[
                            ("inline", "Inline"),
                            ("modal", "Modal"),
                            ("sidebar", "Sidebar"),
                        ],
                        default="inline",
                        help_text="How this block should be edited",
                        max_length=20,
                    ),
                ),
                (
                    "schema",
                    models.JSONField(
                        default=dict, help_text="JSON schema for validating block props"
                    ),
                ),
                (
                    "default_props",
                    models.JSONField(
                        default=dict,
                        help_text="Default props when creating a new instance of this block",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_block_types",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_block_types",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Block Type",
                "verbose_name_plural": "Block Types",
                "db_table": "cms_block_types",
                "ordering": ["category", "label"],
            },
        ),
    ]
