# Generated by Django 4.2.24 on 2025-09-11 13:13

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0018_add_block_type_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="blocktype",
            name="api_endpoint",
            field=models.CharField(
                blank=True,
                help_text='API endpoint for data fetching (e.g., "/api/v1/blog/posts/")',
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="blocktype",
            name="data_source",
            field=models.CharField(
                choices=[
                    ("static", "Static - No data fetching"),
                    ("single", "Single - Select one item"),
                    ("list", "List - Query multiple items"),
                    ("custom", "Custom - Complex data fetching"),
                ],
                default="static",
                help_text="How this block fetches data",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="blocktype",
            name="model_name",
            field=models.CharField(
                blank=True,
                help_text='Model to fetch data from (e.g., "blog.BlogPost", "cms.Page")',
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="blocktype",
            name="query_schema",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Schema for query parameters (filters, ordering, etc.)",
            ),
        ),
    ]
