# Generated by Django 4.2.24 on 2025-09-14 04:59

from django.db import migrations, models

import apps.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0020_add_performance_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="page",
            name="cms_page_homepage_idx",
        ),
        migrations.RemoveIndex(
            model_name="page",
            name="cms_page_menu_idx",
        ),
        migrations.RemoveIndex(
            model_name="page",
            name="cms_page_footer_idx",
        ),
        migrations.RemoveIndex(
            model_name="page",
            name="cms_page_list_idx",
        ),
        migrations.RemoveIndex(
            model_name="page",
            name="cms_page_schedule_pub_idx",
        ),
        migrations.RemoveIndex(
            model_name="page",
            name="cms_page_schedule_unpub_idx",
        ),
        migrations.RemoveIndex(
            model_name="redirect",
            name="cms_redirect_lookup_idx",
        ),
        migrations.AddField(
            model_name="page",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="Categories for organizing this page",
                related_name="pages",
                to="cms.category",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="blocks",
            field=models.JSONField(
                default=list, validators=[apps.core.validators.JSONSizeValidator(2)]
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_review", "Pending Review"),
                    ("published", "Published"),
                    ("scheduled", "Scheduled"),
                    ("rejected", "Rejected"),
                ],
                default="draft",
                max_length=15,
            ),
        ),
    ]
