# Generated by Django 4.2.24 on 2025-09-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0021_remove_page_cms_page_homepage_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blocktype",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Display order in the editor (lower numbers first)"
            ),
        ),
    ]
