# Generated by Django 4.2.24 on 2025-09-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0023_create_default_homepage"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="page",
            constraint=models.UniqueConstraint(
                fields=("locale", "path"), name="uq_page_locale_path"
            ),
        ),
    ]
