# Generated by Django 4.2.24 on 2025-09-07 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("i18n", "0002_alter_locale_options_locale_fallback_and_more"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScopedSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path_prefix",
                    models.CharField(
                        help_text="Path prefix (e.g., '/blog', '/products'). Use '/' for root access.",
                        max_length=255,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for this section (e.g., 'Blog', 'Products')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of what this section includes",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        help_text="Django group to scope",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_scopes",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scoped Section",
                "verbose_name_plural": "Scoped Sections",
                "ordering": ["-path_prefix"],
                "indexes": [
                    models.Index(
                        fields=["group", "path_prefix"],
                        name="accounts_sc_group_i_28b1e8_idx",
                    )
                ],
                "unique_together": {("group", "path_prefix")},
            },
        ),
        migrations.CreateModel(
            name="ScopedLocale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        help_text="Django group to scope",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locale_scopes",
                        to="auth.group",
                    ),
                ),
                (
                    "locale",
                    models.ForeignKey(
                        help_text="Locale this group has access to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_scopes",
                        to="i18n.locale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scoped Locale",
                "verbose_name_plural": "Scoped Locales",
                "indexes": [
                    models.Index(
                        fields=["group", "locale"],
                        name="accounts_sc_group_i_cfae74_idx",
                    )
                ],
                "unique_together": {("group", "locale")},
            },
        ),
    ]
