# Generated by Django 4.2.24 on 2025-09-07 14:43


import django.utils.timezone

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_scopedsection_scopedlocale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_seen",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="Last seen",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="accounts_us_email_74c8d6_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["last_seen"], name="accounts_us_last_se_548692_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["-created_at"], name="accounts_us_created_d650d4_idx"
            ),
        ),
    ]
