# Generated by Django 4.2.24 on 2025-09-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Avatar URL"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="Date of birth"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="language_preference",
            field=models.CharField(
                blank=True,
                default="en",
                max_length=10,
                verbose_name="Language Preference",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Phone number (alt)"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="custom_user_set",
                related_query_name="custom_user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="custom_user_set",
                related_query_name="custom_user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
