# Generated by Django 4.2.24 on 2025-09-07 14:45

import django.contrib.postgres.indexes
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="searchindex",
            index=models.Index(fields=["title"], name="search_sear_title_51a3a1_idx"),
        ),
        migrations.AddIndex(
            model_name="searchindex",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_tags"], name="search_sear_search__dc3f1a_gin"
            ),
        ),
    ]
